# Generated by Django 2.2.6 on 2019-10-30 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountNumber', models.CharField(help_text='Enter a 10-digit account number.', max_length=10, verbose_name='Account Number')),
                ('pin', models.CharField(help_text='Enter a 4-digit pin.', max_length=4, verbose_name='PIN')),
                ('accountName', models.CharField(help_text='Enter account name.', max_length=30, verbose_name='Account Name')),
                ('issueDate', models.CharField(help_text='Enter issue date.', max_length=30, verbose_name='Issue Date')),
                ('expiration_date', models.CharField(help_text='Enter expiration date.', max_length=30, verbose_name='Expiration Date')),
                ('address', models.CharField(help_text='Enter address', max_length=30, verbose_name='Address')),
                ('balance', models.DecimalField(decimal_places=2, help_text='Enter balance.', max_digits=20, verbose_name='Balance')),
                ('cardNumber', models.CharField(help_text='Enter card number.', max_length=16, verbose_name='Card Number')),
                ('phoneNumber', models.CharField(help_text='Enter phone number.', max_length=14, verbose_name='Phone Number')),
                ('cardStatus', models.CharField(blank=True, choices=[('a', 'Active'), ('i', 'Inactive')], default='a', help_text='Select card status.', max_length=1, verbose_name='Card Status')),
            ],
            options={
                'ordering': ['accountNumber'],
            },
        ),
        migrations.CreateModel(
            name='ATM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ATM_UID', models.CharField(help_text='Enter ATM UID', max_length=15, verbose_name='ATM UID')),
                ('ATM_Address', models.CharField(help_text='Enter ATM address.', max_length=30, verbose_name='ATM Address')),
                ('currentBalance', models.DecimalField(decimal_places=2, help_text='Enter current balance.', max_digits=20, verbose_name='Current Balance')),
                ('minimumBalance', models.DecimalField(decimal_places=2, help_text='Enter minimum balance.', max_digits=20, verbose_name='Minimum Balance')),
                ('lastRefillDate', models.CharField(help_text='Enter last refill date.', max_length=30, verbose_name='Last Refill Date')),
                ('nextRefillDate', models.CharField(help_text='Enter next refill date.', max_length=30, verbose_name='Next Refill Date')),
                ('ATM_Status', models.CharField(blank=True, choices=[('a', 'Available'), ('c', 'Closed'), ('l', 'Low')], default='a', help_text='Select ATM status.', max_length=1, verbose_name='ATM Status')),
            ],
            options={
                'ordering': ['ATM_UID'],
            },
        ),
    ]
