# Generated by Django 2.2.6 on 2019-10-30 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_account_atm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='cardStatus',
            field=models.CharField(choices=[('a', 'Active'), ('i', 'Inactive')], default='a', help_text='Select card status.', max_length=1, verbose_name='Card Status'),
        ),
        migrations.AlterField(
            model_name='atm',
            name='ATM_Status',
            field=models.CharField(choices=[('a', 'Available'), ('c', 'Closed'), ('l', 'Low')], default='a', help_text='Select ATM status.', max_length=1, verbose_name='ATM Status'),
        ),
    ]
